"""revmoed date_created unique constraint from BuildIDs table

Revision ID: 1f827c48dd96
Revises: a8108f3b6963
Create Date: 2023-07-26 10:25:33.008247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f827c48dd96'
down_revision = 'a8108f3b6963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_ids', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_build_ids', type_='unique')
        batch_op.create_unique_constraint('_unique_build_ids', ['voltage_id', 'temperature_id', 'unit_id', 'test_id', 'project_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_ids', schema=None) as batch_op:
        batch_op.drop_constraint('_unique_build_ids', type_='unique')
        batch_op.create_unique_constraint('_unique_build_ids', ['date_created', 'voltage_id', 'temperature_id', 'unit_id', 'test_id', 'project_id'])

    # ### end Alembic commands ###
