"""Edited BuildIDs timestamp to current date/time, removed run time

Revision ID: 34fd8b114034
Revises: d3b2801f2277
Create Date: 2023-07-24 17:23:51.090758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fd8b114034'
down_revision = 'd3b2801f2277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('_unique_build_ids', type_='unique')
        batch_op.create_unique_constraint('_unique_build_ids', ['date_created', 'voltage_id', 'temperature_id', 'unit_id', 'test_id', 'project_id'])
        batch_op.drop_column('time_stamp')
        batch_op.drop_column('run_time')
        batch_op.drop_column('test_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_status', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('run_time', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('time_stamp', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('_unique_build_ids', type_='unique')
        batch_op.create_unique_constraint('_unique_build_ids', ['time_stamp', 'voltage_id', 'temperature_id', 'unit_id', 'test_id', 'project_id'])
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
