"""added device dna column in Units table

Revision ID: 6e8dfabd63ab
Revises: 1f827c48dd96
Create Date: 2023-08-08 10:28:31.720136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8dfabd63ab'
down_revision = '1f827c48dd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_dna', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('device_dna')

    # ### end Alembic commands ###
