"""Added target unit count column to Projects table

Revision ID: 8392861b4aa2
Revises: 6e8dfabd63ab
Create Date: 2023-09-26 10:46:37.464102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8392861b4aa2'
down_revision = '6e8dfabd63ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_unit_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('target_unit_count')

    # ### end Alembic commands ###
