"""Edit Tests table (test list)

Revision ID: 8ae72fab2df5
Revises: c8f8b361d0e9
Create Date: 2023-07-24 10:46:55.917642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae72fab2df5'
down_revision = 'c8f8b361d0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
