"""added unit_id column in TestInstance table

Revision ID: a8108f3b6963
Revises: 5df82ee17f9c
Create Date: 2023-07-26 09:14:17.419308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8108f3b6963"
down_revision = "5df82ee17f9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_instances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("unit_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint("_unique_test_instances", type_="unique")
        batch_op.create_unique_constraint(
            "_unique_test_instances",
            [
                "project_id",
                "unit_id",
                "voltage_id",
                "temperature_id",
                "test_id",
                "s_suite",
                "suite",
                "test_name",
            ],
        )
        batch_op.create_foreign_key(
            "fk_test_instances_unit_id", "units", ["unit_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_instances", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint("_unique_test_instances", type_="unique")
        batch_op.create_unique_constraint(
            "_unique_test_instances",
            [
                "project_id",
                "voltage_id",
                "temperature_id",
                "test_id",
                "s_suite",
                "suite",
                "test_name",
            ],
        )
        batch_op.drop_column("unit_id")

    # ### end Alembic commands ###
