"""Added project_id in BuildIds table

Revision ID: c8f8b361d0e9
Revises: b7c7350199ce
Create Date: 2023-06-28 15:40:13.044871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8f8b361d0e9"
down_revision = "b7c7350199ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("build_ids", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_build_ids_project_id", "projects", ["project_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("build_ids", schema=None) as batch_op:
        batch_op.drop_constraint("fk_build_ids_project_id", type_="foreignkey")
        batch_op.drop_column("project_id")

    # ### end Alembic commands ###
